ExhibitionTimeMachine/config/routes.rb
Rails.application.routes.draw do
  resources :artists
  resources :artworks

end

ExhibitionTimeMachine/app/models/artist.rb
class Artist < ActiveRecord::Base
end

ExhibitionTimeMachine/app/models/artwork.rb
class Artwork < ActiveRecord::Base
end

ExhibitionTimeMachine/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ExhibitionTimeMachine/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :dob, :dod, :bio)
    end
end

ExhibitionTimeMachine/app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: [:show, :edit, :update, :destroy]

  # GET /artworks
  # GET /artworks.json
  def index
    @artworks = Artwork.all
  end

  # GET /artworks/1
  # GET /artworks/1.json
  def show
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
  end

  # POST /artworks
  # POST /artworks.json
  def create
    @artwork = Artwork.new(artwork_params)

    respond_to do |format|
      if @artwork.save
        format.html { redirect_to @artwork, notice: 'Artwork was successfully created.' }
        format.json { render :show, status: :created, location: @artwork }
      else
        format.html { render :new }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artworks/1
  # PATCH/PUT /artworks/1.json
  def update
    respond_to do |format|
      if @artwork.update(artwork_params)
        format.html { redirect_to @artwork, notice: 'Artwork was successfully updated.' }
        format.json { render :show, status: :ok, location: @artwork }
      else
        format.html { render :edit }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1
  # DELETE /artworks/1.json
  def destroy
    @artwork.destroy
    respond_to do |format|
      format.html { redirect_to artworks_url, notice: 'Artwork was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artwork
      @artwork = Artwork.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artwork_params
      params.require(:artwork).permit(:title, :description, :artist_id, :images_dir)
    end
end

ExhibitionTimeMachine/app/helpers/application_helper.rb
module ApplicationHelper
end

ExhibitionTimeMachine/app/helpers/artists_helper.rb
module ArtistsHelper
end

ExhibitionTimeMachine/app/helpers/artworks_helper.rb
module ArtworksHelper
end

ExhibitionTimeMachine/app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="field">
    <%= f.label :dod %><br>
    <%= f.date_select :dod %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ExhibitionTimeMachine/app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

ExhibitionTimeMachine/app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dob</th>
      <th>Dod</th>
      <th>Bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.dob %></td>
        <td><%= artist.dod %></td>
        <td><%= artist.bio %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

ExhibitionTimeMachine/app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

ExhibitionTimeMachine/app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @artist.dob %>
</p>

<p>
  <strong>Dod:</strong>
  <%= @artist.dod %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @artist.bio %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

ExhibitionTimeMachine/app/views/artworks/_form.html.erb
<%= form_for(@artwork) do |f| %>
  <% if @artwork.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
      <% @artwork.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :artist_id %><br>
    <%= f.text_field :artist_id %>
  </div>
  <div class="field">
    <%= f.label :images_dir %><br>
    <%= f.text_field :images_dir %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ExhibitionTimeMachine/app/views/artworks/edit.html.erb
<h1>Editing Artwork</h1>

<%= render 'form' %>

<%= link_to 'Show', @artwork %> |
<%= link_to 'Back', artworks_path %>

ExhibitionTimeMachine/app/views/artworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artworks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Artist</th>
      <th>Images dir</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artworks.each do |artwork| %>
      <tr>
        <td><%= artwork.title %></td>
        <td><%= artwork.description %></td>
        <td><%= artwork.artist_id %></td>
        <td><%= artwork.images_dir %></td>
        <td><%= link_to 'Show', artwork %></td>
        <td><%= link_to 'Edit', edit_artwork_path(artwork) %></td>
        <td><%= link_to 'Destroy', artwork, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artwork', new_artwork_path %>

ExhibitionTimeMachine/app/views/artworks/new.html.erb
<h1>New Artwork</h1>

<%= render 'form' %>

<%= link_to 'Back', artworks_path %>

ExhibitionTimeMachine/app/views/artworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @artwork.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @artwork.description %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @artwork.artist_id %>
</p>

<p>
  <strong>Images dir:</strong>
  <%= @artwork.images_dir %>
</p>

<%= link_to 'Edit', edit_artwork_path(@artwork) %> |
<%= link_to 'Back', artworks_path %>

ExhibitionTimeMachine/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExhibitionTimeMachine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>